### ISSUE TITLE
episode 25 - adding pylint and nbqa to requirements

### ISSUE THREAD

**Issue by mpgh** [ShrRa/python-intermediate-development#11]
Without adding pylint and nbqa to the requirements the build will stop:

Run python3 -m pylint --fail-under=0 --reports=y lcanalyzer
/opt/hostedtoolcache/Python/3.11.9/x64/bin/python3: No module named pylint
Error: Process completed with exit code 1.

etc.

CI will pass successfully after updating the requirements.txt. Adding this from the start might avoid similar issues.

**Comment by RileyWClarke** [comment]
Aren't pylint and nbqa already supposed to be added to the requirements back in Section 1? 
<img width="1167" alt="Screenshot 2024-07-02 at 12 48 21 PM" src="https://github.com/ShrRa/python-intermediate-development/assets/17172556/46993d9d-70c9-4106-b3d1-f285c04f7b91">

**Comment by mpgh** [comment]
you are right. When going through the material, I must have skipped the freeze. Accordingly, if other participants skip this step the issue will appear
