### ISSUE TITLE
Add context for new function example

### ISSUE THREAD

**Issue by rachel3834** [ShrRa/python-intermediate-development#14]
In the Setting the Scene section of the [Issue Diagnostics](https://shrra.github.io/python-intermediate-development/25-diagnosing-issues-improving-robustness/index.html) chapter, the instructions would benefit from clarifying whether the new function should be added to an existing file or as a new file and if so, in what part of the directory structure.

**Comment by RileyWClarke** [comment]
I believe the intent is for the new function to be added to light-curve-analysis.ipynb, since there is an optional exercise later to move it to lcanalyzer/models.py and add an associated test in tests/test_models.py. Context added in 37ce4276e1942c635801ef3519c007443082535f.
